/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.BBS
-- 만든 날짜: 2017-02-27 오후 11:48:02
-- 마지막으로 수정한 날짜: 2017-05-23 오후 2:30:12
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE HYUNS00.BBS CASCADE CONSTRAINTS;

CREATE TABLE HYUNS00.BBS (
  NO            NUMBER                  NOT NULL,
  PRE_NO        NUMBER                  NOT NULL,
  SUB_NO        NUMBER                  NOT NULL,
  DEP_NO        NUMBER                  NOT NULL,
  COM_COUNT     NUMBER                  NOT NULL,
  VIEW_COUNT    NUMBER                  NOT NULL,
  BBS_ID        NVARCHAR2(20 CHAR)      NOT NULL,
  USER_ID       NVARCHAR2(200 CHAR)         NULL,
  USER_PW       NVARCHAR2(200 CHAR)     NOT NULL,
  USER_NAME     NVARCHAR2(200 CHAR)     NOT NULL,
  USER_EMAIL    NVARCHAR2(200 CHAR)         NULL,
  USER_IP       NVARCHAR2(200 CHAR)     NOT NULL,
  SUBJECT       NVARCHAR2(200 CHAR)     NOT NULL,
  NOTICE_YN     CHAR(1 BYTE)            NOT NULL,
  REG_DATE      DATE                    NOT NULL,
  CONTENT       CLOB                    NOT NULL
)
LOB (CONTENT) STORE AS (
    TABLESPACE USERS
    ENABLE STORAGE IN ROW
    CHUNK 8192
    NOCACHE
    LOGGING
    STORAGE (
        INITIAL     64K
        NEXT        1M
        MINEXTENTS  1
        MAXEXTENTS  UNLIMITED
    )
)
TABLESPACE USERS
PCTFREE    10
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE HYUNS00.BBS IS '게시판';

COMMENT ON COLUMN HYUNS00.BBS.NO IS '글번호';

COMMENT ON COLUMN HYUNS00.BBS.PRE_NO IS '위글번호';

COMMENT ON COLUMN HYUNS00.BBS.SUB_NO IS '글정렬';

COMMENT ON COLUMN HYUNS00.BBS.DEP_NO IS '글단계';

COMMENT ON COLUMN HYUNS00.BBS.COM_COUNT IS '댓글개수';

COMMENT ON COLUMN HYUNS00.BBS.VIEW_COUNT IS '읽은숫자';

COMMENT ON COLUMN HYUNS00.BBS.BBS_ID IS '게시판명';

COMMENT ON COLUMN HYUNS00.BBS.USER_ID IS '유저ID';

COMMENT ON COLUMN HYUNS00.BBS.USER_PW IS '비밀번호';

COMMENT ON COLUMN HYUNS00.BBS.USER_NAME IS '글쓴이';

COMMENT ON COLUMN HYUNS00.BBS.USER_EMAIL IS '이메일';

COMMENT ON COLUMN HYUNS00.BBS.USER_IP IS '제목';

COMMENT ON COLUMN HYUNS00.BBS.SUBJECT IS '유저IP';

COMMENT ON COLUMN HYUNS00.BBS.NOTICE_YN IS '공지글';

COMMENT ON COLUMN HYUNS00.BBS.REG_DATE IS '등록일자';

COMMENT ON COLUMN HYUNS00.BBS.CONTENT IS '내용';

/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.IX_BBS_ID_NOTICE_YN
-- 만든 날짜: 2017-05-23 오후 2:30:12
-- 마지막으로 수정한 날짜: 2017-05-23 오후 2:30:12
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP INDEX HYUNS00.IX_BBS_ID_NOTICE_YN;

CREATE INDEX HYUNS00.IX_BBS_ID_NOTICE_YN
ON HYUNS00.BBS (BBS_ID, NOTICE_YN)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
)
TABLESPACE USERS
LOGGING
NOPARALLEL;

ALTER TABLE HYUNS00.BBS ADD
(
    CONSTRAINT PK_BBS
    PRIMARY KEY ( NO )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);
/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.BBS_CATE
-- 만든 날짜: 2017-05-18 오후 5:52:33
-- 마지막으로 수정한 날짜: 2017-05-20 오전 11:24:14
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE HYUNS00.BBS_CATE CASCADE CONSTRAINTS;

CREATE TABLE HYUNS00.BBS_CATE (
  NO           NUMBER                  NOT NULL,
  BBS_ID       NVARCHAR2(200 CHAR)     NOT NULL,
  BBS_NAME     NVARCHAR2(200 CHAR)     NOT NULL,
  LIST_SIZE    NUMBER                  NOT NULL,
  PAGE_SIZE    NUMBER                  NOT NULL,
  USE_YN       CHAR(1 BYTE)           DEFAULT 'Y'            NOT NULL,
  REG_DATE     DATE                    NOT NULL
)
TABLESPACE USERS
PCTFREE    10
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE HYUNS00.BBS_CATE IS '분류';

COMMENT ON COLUMN HYUNS00.BBS_CATE.NO IS '번호';

COMMENT ON COLUMN HYUNS00.BBS_CATE.BBS_ID IS '게시판ID';

COMMENT ON COLUMN HYUNS00.BBS_CATE.BBS_NAME IS '게시판명';

COMMENT ON COLUMN HYUNS00.BBS_CATE.LIST_SIZE IS '리스트 갯수';

COMMENT ON COLUMN HYUNS00.BBS_CATE.PAGE_SIZE IS '페이지 갯수';

COMMENT ON COLUMN HYUNS00.BBS_CATE.USE_YN IS '사용유무';

COMMENT ON COLUMN HYUNS00.BBS_CATE.REG_DATE IS '등록일';

ALTER TABLE HYUNS00.BBS_CATE ADD
(
    CONSTRAINT PK_BBS_CATE
    PRIMARY KEY ( NO )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);

ALTER TABLE HYUNS00.BBS_CATE ADD
(
    CONSTRAINT UNI_BBS_CATE
    UNIQUE ( BBS_ID )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);
/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.BBS_COMMENT
-- 만든 날짜: 2017-02-27 오후 11:48:06
-- 마지막으로 수정한 날짜: 2017-04-13 오후 4:23:31
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE HYUNS00.BBS_COMMENT CASCADE CONSTRAINTS;

CREATE TABLE HYUNS00.BBS_COMMENT (
  NO           NUMBER                  NOT NULL,
  PNO          NUMBER                  NOT NULL,
  PRE_NO       NUMBER                  NOT NULL,
  SUB_NO       NUMBER                  NOT NULL,
  DEP_NO       NUMBER                  NOT NULL,
  USER_ID      NVARCHAR2(200 CHAR)         NULL,
  USER_PW      NVARCHAR2(200 CHAR)     NOT NULL,
  USER_NAME    NVARCHAR2(200 CHAR)     NOT NULL,
  USER_IP      NVARCHAR2(200 CHAR)     NOT NULL,
  REG_DATE     DATE                    NOT NULL,
  CONTENT      CLOB                    NOT NULL
)
LOB (CONTENT) STORE AS (
    TABLESPACE USERS
    ENABLE STORAGE IN ROW
    CHUNK 8192
    NOCACHE
    LOGGING
    STORAGE (
        INITIAL     64K
        NEXT        1M
        MINEXTENTS  1
        MAXEXTENTS  UNLIMITED
    )
)
TABLESPACE USERS
PCTFREE    10
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE HYUNS00.BBS_COMMENT IS '덧글';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.CONTENT IS '내용';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.NO IS '덧글번호';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.PNO IS '부모글번호';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.PRE_NO IS '위덧글번호';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.SUB_NO IS '덧글정렬';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.DEP_NO IS '덧글단계';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.USER_ID IS '유저ID';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.USER_PW IS '비밀번호';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.USER_NAME IS '글쓴이';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.USER_IP IS '유저IP';

COMMENT ON COLUMN HYUNS00.BBS_COMMENT.REG_DATE IS '등록일자';

/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.PK_BBS_COMMENT
-- 만든 날짜: 2017-02-27 오후 11:48:07
-- 마지막으로 수정한 날짜: 2017-02-27 오후 11:48:07
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP INDEX HYUNS00.PK_BBS_COMMENT;

CREATE UNIQUE INDEX HYUNS00.PK_BBS_COMMENT
ON HYUNS00.BBS_COMMENT (NO)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
)
TABLESPACE USERS
LOGGING
NOPARALLEL;

ALTER TABLE HYUNS00.BBS_COMMENT ADD
(
    CONSTRAINT PK_BBSCOMMENT
    PRIMARY KEY ( NO )
);
/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.BBS_FILE
-- 만든 날짜: 2017-03-21 오후 9:43:16
-- 마지막으로 수정한 날짜: 2017-05-19 오후 1:47:56
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE HYUNS00.BBS_FILE CASCADE CONSTRAINTS;

CREATE TABLE HYUNS00.BBS_FILE (
  NO            NUMBER                  NOT NULL,
  PNO           NUMBER                  NOT NULL,
  FILE_BASE     NVARCHAR2(200 CHAR)     NOT NULL,
  FILE_PATH     NVARCHAR2(200 CHAR)     NOT NULL,
  FILE_NAME     NVARCHAR2(200 CHAR)     NOT NULL,
  SAVE_NAME     NVARCHAR2(200 CHAR)     NOT NULL,
  FILE_SIZE     NUMBER                  NOT NULL,
  DOWN_COUNT    NUMBER                  NOT NULL
)
TABLESPACE USERS
PCTFREE    10
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE HYUNS00.BBS_FILE IS '업로드';

COMMENT ON COLUMN HYUNS00.BBS_FILE.NO IS '파일번호';

COMMENT ON COLUMN HYUNS00.BBS_FILE.PNO IS '글번호';

COMMENT ON COLUMN HYUNS00.BBS_FILE.FILE_BASE IS '기본경로';

COMMENT ON COLUMN HYUNS00.BBS_FILE.FILE_PATH IS '파일경로';

COMMENT ON COLUMN HYUNS00.BBS_FILE.FILE_NAME IS '파일명';

COMMENT ON COLUMN HYUNS00.BBS_FILE.SAVE_NAME IS '저장파일명';

COMMENT ON COLUMN HYUNS00.BBS_FILE.FILE_SIZE IS '파일크기';

COMMENT ON COLUMN HYUNS00.BBS_FILE.DOWN_COUNT IS '다운숫자';

ALTER TABLE HYUNS00.BBS_FILE ADD
(
    CONSTRAINT PK_BBS_FILE
    PRIMARY KEY ( NO )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);
/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.BBS_SCRAP
-- 만든 날짜: 2017-04-11 오후 9:50:38
-- 마지막으로 수정한 날짜: 2017-05-20 오후 12:31:14
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE HYUNS00.BBS_SCRAP CASCADE CONSTRAINTS;

CREATE TABLE HYUNS00.BBS_SCRAP (
  NO          NUMBER                 NOT NULL,
  PNO         NUMBER                 NOT NULL,
  BBS_ID      NVARCHAR2(20 CHAR)     NOT NULL,
  USER_ID     NVARCHAR2(20 CHAR)     NOT NULL,
  REG_DATE    DATE                   NOT NULL
)
TABLESPACE USERS
PCTFREE    10
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE HYUNS00.BBS_SCRAP IS '스크랩';

COMMENT ON COLUMN HYUNS00.BBS_SCRAP.NO IS '번호';

COMMENT ON COLUMN HYUNS00.BBS_SCRAP.PNO IS '게시판번호';

COMMENT ON COLUMN HYUNS00.BBS_SCRAP.BBS_ID IS '게시판명';

COMMENT ON COLUMN HYUNS00.BBS_SCRAP.USER_ID IS '등록 유저 ID';

COMMENT ON COLUMN HYUNS00.BBS_SCRAP.REG_DATE IS '등록일';

ALTER TABLE HYUNS00.BBS_SCRAP ADD
(
    CONSTRAINT PK_BBS_SCRAP
    PRIMARY KEY ( NO )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);
/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.LOGIN
-- 만든 날짜: 2017-03-01 오후 11:49:24
-- 마지막으로 수정한 날짜: 2017-05-19 오후 1:49:49
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE HYUNS00.LOGIN CASCADE CONSTRAINTS;

CREATE TABLE HYUNS00.LOGIN (
  USER_NO        NUMBER                  NOT NULL,
  USER_ID        NVARCHAR2(100 CHAR)     NOT NULL,
  USER_PW        NVARCHAR2(100 CHAR)     NOT NULL,
  USER_NAME      NVARCHAR2(100 CHAR)     NOT NULL,
  USER_ROLE      NVARCHAR2(200 CHAR)     NOT NULL,
  USER_EMAIL     NVARCHAR2(200 CHAR)     NOT NULL,
  USER_NICK      NVARCHAR2(100 CHAR)     NOT NULL,
  IMAGE_PATH     NVARCHAR2(200 CHAR)         NULL,
  IMAGE_NAME     NVARCHAR2(200 CHAR)         NULL,
  JOIN_DATE      DATE                    NOT NULL,
  LAST_DATE      DATE                        NULL,
  EXIT_DATE      DATE                        NULL,
  EXIT_YN        CHAR(1 BYTE)            NOT NULL,
  VISIT_COUNT    NUMBER                  NOT NULL
)
TABLESPACE USERS
PCTFREE    10
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE HYUNS00.LOGIN IS '로그인';

COMMENT ON COLUMN HYUNS00.LOGIN.USER_NO IS '유저번호';

COMMENT ON COLUMN HYUNS00.LOGIN.USER_ID IS '유저ID';

COMMENT ON COLUMN HYUNS00.LOGIN.USER_PW IS '비밀번호';

COMMENT ON COLUMN HYUNS00.LOGIN.USER_NAME IS '유저명';

COMMENT ON COLUMN HYUNS00.LOGIN.USER_ROLE IS '권한';

COMMENT ON COLUMN HYUNS00.LOGIN.USER_EMAIL IS '이메일';

COMMENT ON COLUMN HYUNS00.LOGIN.USER_NICK IS '닉네임';

COMMENT ON COLUMN HYUNS00.LOGIN.IMAGE_PATH IS '이미지경로';

COMMENT ON COLUMN HYUNS00.LOGIN.IMAGE_NAME IS '이미지명';

COMMENT ON COLUMN HYUNS00.LOGIN.JOIN_DATE IS '가입일시';

COMMENT ON COLUMN HYUNS00.LOGIN.LAST_DATE IS '접속일시';

COMMENT ON COLUMN HYUNS00.LOGIN.EXIT_DATE IS '탈퇴일시';

COMMENT ON COLUMN HYUNS00.LOGIN.EXIT_YN IS '탈퇴유무';

COMMENT ON COLUMN HYUNS00.LOGIN.VISIT_COUNT IS '방문횟수';

ALTER TABLE HYUNS00.LOGIN ADD
(
    CONSTRAINT PK_LOGIN
    PRIMARY KEY ( USER_NO )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);

ALTER TABLE HYUNS00.LOGIN ADD
(
    CONSTRAINT UNI_LOGIN
    UNIQUE ( USER_ID, USER_EMAIL, USER_NICK )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);
/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.MENU
-- 만든 날짜: 2017-05-19 오후 1:55:44
-- 마지막으로 수정한 날짜: 2017-05-20 오전 11:23:51
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE HYUNS00.MENU CASCADE CONSTRAINTS;

CREATE TABLE HYUNS00.MENU (
  NO           NUMBER                  NOT NULL,
  MENU_ID      NVARCHAR2(20 CHAR)      NOT NULL,
  MENU_NAME    NVARCHAR2(200 CHAR)     NOT NULL,
  USE_YN       CHAR(1 BYTE)           DEFAULT 'Y'            NOT NULL,
  REG_DATE     DATE                    NOT NULL
)
TABLESPACE USERS
PCTFREE    10
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE HYUNS00.MENU IS '메뉴';

COMMENT ON COLUMN HYUNS00.MENU.NO IS '번호';

COMMENT ON COLUMN HYUNS00.MENU.MENU_ID IS '그룹ID';

COMMENT ON COLUMN HYUNS00.MENU.MENU_NAME IS '그룹명';

COMMENT ON COLUMN HYUNS00.MENU.USE_YN IS '사용유무';

COMMENT ON COLUMN HYUNS00.MENU.REG_DATE IS '등록일';

/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.UNI_BBS_GROUP
-- 만든 날짜: 2017-05-19 오후 1:55:44
-- 마지막으로 수정한 날짜: 2017-05-19 오후 1:55:44
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP INDEX HYUNS00.UNI_BBS_GROUP;

CREATE UNIQUE INDEX HYUNS00.UNI_BBS_GROUP
ON HYUNS00.MENU (MENU_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
)
TABLESPACE USERS
LOGGING
NOPARALLEL;

/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.PK_BBS_GROUP
-- 만든 날짜: 2017-05-19 오후 1:56:05
-- 마지막으로 수정한 날짜: 2017-05-19 오후 1:56:05
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP INDEX HYUNS00.PK_BBS_GROUP;

CREATE UNIQUE INDEX HYUNS00.PK_BBS_GROUP
ON HYUNS00.MENU (NO)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
)
TABLESPACE USERS
LOGGING
NOPARALLEL;

ALTER TABLE HYUNS00.MENU ADD
(
    CONSTRAINT PK_BBS_MENU
    PRIMARY KEY ( NO )
);

ALTER TABLE HYUNS00.MENU ADD
(
    CONSTRAINT UNI_BBS_MENU
    UNIQUE ( MENU_ID )
);
/*------------------------------------------------------------------------------
-- 개체 이름: HYUNS00.MESSAGE
-- 만든 날짜: 2017-05-19 오후 1:44:04
-- 마지막으로 수정한 날짜: 2017-05-19 오후 1:44:04
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE HYUNS00.MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE HYUNS00.MESSAGE (
  NO            NUMBER                 NOT NULL,
  PNO           NUMBER                 NOT NULL,
  SEND_ID       VARCHAR2(100 BYTE)     NOT NULL,
  RECEIVE_ID    VARCHAR2(100 BYTE)     NOT NULL,
  SUBJECT       VARCHAR2(200 BYTE)     NOT NULL,
  REG_DATE      DATE                   NOT NULL,
  CONTENT       CLOB                   NOT NULL
)
LOB (CONTENT) STORE AS (
    TABLESPACE USERS
    ENABLE STORAGE IN ROW
    CHUNK 8192
    NOCACHE
    LOGGING
    STORAGE (
        INITIAL     64K
        NEXT        1M
        MINEXTENTS  1
        MAXEXTENTS  UNLIMITED
    )
)
TABLESPACE USERS
PCTFREE    10
PCTUSED    0
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE HYUNS00.MESSAGE IS '메시지';

COMMENT ON COLUMN HYUNS00.MESSAGE.NO IS '번호';

COMMENT ON COLUMN HYUNS00.MESSAGE.PNO IS '부모번호';

COMMENT ON COLUMN HYUNS00.MESSAGE.SEND_ID IS '보낸 ID';

COMMENT ON COLUMN HYUNS00.MESSAGE.RECEIVE_ID IS '받은 ID';

COMMENT ON COLUMN HYUNS00.MESSAGE.SUBJECT IS '제목';

COMMENT ON COLUMN HYUNS00.MESSAGE.REG_DATE IS '등록일';

COMMENT ON COLUMN HYUNS00.MESSAGE.CONTENT IS '내용';

ALTER TABLE HYUNS00.MESSAGE ADD
(
    CONSTRAINT PK_MESSAGE
    PRIMARY KEY ( NO )
        USING INDEX
        TABLESPACE USERS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
        )
);